# CH - 9 Advanced OOPS and Numpy

### Polymorphism
    poly = many
    morph = forms

### Overloading - compile time polymorphism(not possible in python)
    # It occurs in same class
    # methods must have the same name and different parameters
    # Python does not support method Overloading

### Overriding - runtime polymorphism
     # It occurs in deifferent classes via inheritance
     # Methods must have same name and same parameters
     # Python supports method Overriding

### Examples of method Overloading

In [5]:
class Shape:
    def area(self,a):
        return 3.14*a*a
    def area(self,a,b):
        return a*b
s = Shape()
print(s.area(3,4))
print(s.area(2,))

12


TypeError: area() missing 1 required positional argument: 'b'

In [7]:
class Shape:
    def area(self,a):
        return 3.14*a*a
    def area(self,a,b):
        return a*b
s = Shape()
print(s.area(2,))
print(s.area(3,4))

TypeError: area() missing 1 required positional argument: 'b'

In [8]:
class Shape:
    def area(self,a):
        return 3.14*a*a
    def area(self,a,b):
        return a*b
s = Shape()
print(s.area(2,2))
print(s.area(3,4))

4
12


### Explanation of Method Overriding

In [11]:
class Add:
    def result(self,a,b):
        print("Addition = ",a+b)
class Multi(Add):
    def result(self,a,b):
        super().result(a,b)
        print("Multiplication = ",a*b)
a = Multi()
a.result(2,3)
m = Add()
m.result(2,3)

Addition =  5
Multiplication =  6
Addition =  5


In [15]:
class A:
    def first(self):
        print("First Function of class A")
    def second(self):
        print("Second Function of class A")
class B(A):
    def first(self):
        print("First Function of class B")
    def display(self):
        print("Display Function of class B")
obj1 = A()
obj2 = B()
obj1.first()
obj2.first()
obj1.second()
obj2.second()
obj2.display()
# obj1.display()

First Function of class A
First Function of class B
Second Function of class A
Second Function of class A
Display Function of class B


### Explanation of Operator Overloading
    --> Giving extended meaning beyond their predefined meaning

In [17]:
class A:
    def __init__(self,x):
        self.x = x
    def __add__(self,other):
        return self.x + other.x
class B:
    def __init__(self,x):
        self.x = x
a = A(100)
b = B(200)
print(a+b)

300


In [19]:
class A:
    def __init__(self,a):
        self.a = a
    def __add__(self,other):
        return self.a+other.a
obj1 = A(1)
obj2 = A(1)
obj3 = A("Hello")
obj4 = A("Hi")
print(obj1+obj2)
print(obj3+obj4)
print(A.__add__(obj1,obj2))
print(A.__add__(obj3,obj4))
print(obj1.__add__(obj2))
print(obj3.__add__(obj4))

2
HelloHi
2
HelloHi
2
HelloHi


In [20]:
class A:
    def __init__(self,a):
        self.a = a
    def __gt__(self,other):
        if self.a > other.a:
            return True
        else:
            return False
obj1 = A(2)
obj2 = A(3)

if obj1 > obj2:
    print("Obj1 is greater than obj2")
else:
    print("obj2 is greater than obj1")

obj2 is greater than obj1


### Mathematical Operators
    +	__add__(self, other)	a + b
    -	__sub__(self, other)	a - b
    *	__mul__(self, other)	a * b
    /	__truediv__(self, other)	a / b
    //	__floordiv__(self, other)	a // b
    %	__mod__(self, other)	a % b
    **	__pow__(self, other)	a ** b

###  Comparision Operators
    ==	__eq__(self, other)	a == b
    !=	__ne__(self, other)	a != b
    <	__lt__(self, other)	a < b
    <=	__le__(self, other)	a <= b
    >	__gt__(self, other)	a > b
    >=	__ge__(self, other)	a >= b


    [] (Indexing)	__getitem__(self, key)	a[key]
    [] (Assignment)	__setitem__(self, key, value)	a[key] = value
    len()	__len__(self)	len(a)
    str()	__str__(self)	str(a)
    repr()	__repr__(self)	repr(a)

### Inheritance
    --> Ability to inherit features or attributes from already written classes into newer classes we make
    --> These features and attributes are defined data structures and the functions we can perform with them
    --> It promotes code reusability

### Single Inheritance

In [26]:
class parent:
    def fun1(self):
        print("Hello Parent")
class child(parent):
    def fun2(self):
        print("Hello Child")
test = child()
test.fun1()
test.fun2()

Hello Parent
Hello Child


In [27]:
class parent:
    def fun1(self):
        print("Hello Parent")
class child(parent):
    def fun2(self):
        super().fun1()
        print("Hello Child")
test = child()
test.fun2()

Hello Parent
Hello Child


In [28]:
class parent:
    def fun1(self):
        print("Hello Parent")
class child(parent):
    def fun2(self):
        print("Hello Child")
        super().fun1()
test = child()
test.fun2()

Hello Child
Hello Parent


### Multiple Inheritance

In [29]:
class parent1:
    def fun1(self):
        print("Hello Parent 1")
class parent2:
    def fun2(self):
        print("Hello Parent 2")
class parent3:
    def fun2(self):
        print("Hello Parent 3")
class child(parent1,parent2,parent3):
    def fun3(self):
        print("Hello Child")
test = child()
test.fun1()
test.fun2()
test.fun3()
print(child.__mro__)

Hello Parent 1
Hello Parent 2
Hello Child
(<class '__main__.child'>, <class '__main__.parent1'>, <class '__main__.parent2'>, <class '__main__.parent3'>, <class 'object'>)


### Multi-Level Inheritance

In [3]:
class grandparent:
    def fun1(self):
        print("Hello Grandfather")
class parent(grandparent):
    def fun2(self):
        print("Hello Parent")
class child(parent):
    def fun3(self):
        print("Hello Child")
test = child()
test.fun1()
test.fun2()
test.fun3()
print(child.__mro__)

Hello Grandfather
Hello Parent
Hello Child
(<class '__main__.child'>, <class '__main__.parent'>, <class '__main__.grandparent'>, <class 'object'>)


### Hierarchical Inheritance

In [4]:
class parent:
    def fun1(self):
        print("Hello Parent")
class child1(parent):
    def fun2(self):
        print("Hello Child1")
class child2(parent):
    def fun3(self):
        print("Hello Child2")
p_obj = parent()
c1 = child1()
c2 = child2()

p_obj.fun1()
c1.fun1()
c1.fun2()
c2.fun1()
c2.fun3()
print(child1.__mro__)
print(child2.__mro__)

Hello Parent
Hello Parent
Hello Child1
Hello Parent
Hello Child2
(<class '__main__.child1'>, <class '__main__.parent'>, <class 'object'>)
(<class '__main__.child2'>, <class '__main__.parent'>, <class 'object'>)


### Hybrid Inheritance

In [6]:
class parent1:
    def fun1(self):
        print("Hello Parent1")
class parent2:
    def fun2(self):
        print("Hello Parent2")
class child1(parent1):
    def fun3(self):
        print("Hello Child1")
class child2(child1,parent2):
    def fun4(self):
        print("Hello Child2")
test1 = child1()
test2 = child2()

test1.fun1()

test2.fun1()
test2.fun2()
test2.fun3()
test2.fun4()

print(child1.__mro__)
print(child2.__mro__)
print(parent1.mro())

Hello Parent1
Hello Parent1
Hello Parent2
Hello Child1
Hello Child2
(<class '__main__.child1'>, <class '__main__.parent1'>, <class 'object'>)
(<class '__main__.child2'>, <class '__main__.child1'>, <class '__main__.parent1'>, <class '__main__.parent2'>, <class 'object'>)
[<class '__main__.parent1'>, <class 'object'>]


### Super Function

In [13]:
class parent:
    def __init__(self):
        self.attr1 = 50
        self.attr2 = 65
class child(parent):
    def __init__(self):
        super().__init__()
        self.attr3 = 45
        parent.__init__(self)
test = child()
print(test.attr1)

50


In [1]:
class parent:
    def __init__(self):
        self.attr1 = 50
        self.attr2 = 65
class child():
    def __init__(self):
        super().__init__()
        self.attr3 = 45
#         parent.__init__(self)
test = child()
print(test.attr1)

AttributeError: 'child' object has no attribute 'attr1'

In [ ]:
class parent:
    def __init__(self):
        self.attr1 = 50
        self.attr2 = 65
class child():
    def __init__(self):
        parent.__init__(self)
        self.attr3 = 45
test = child()
print(test.attr1)

### issubclass() and isinstance()

In [ ]:
class parent:
    def fun1(self):
        print("Hello Parent")
class child(parent):
    def fun2(self):
        print("Hello Child")
print(issubclass(child,parent))

In [5]:
class p1:
    def foo(self):
        print("foo from p1")
        
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")

class c1(p1):
    pass
class c2(p2):
    def bar(self):
        print("bar from c2")
        
class GC(c1,c2):
    pass

gc = GC()
gc.bar()
gc.foo()
print(GC.__mro__)


bar from c2
foo from p1
(<class '__main__.GC'>, <class '__main__.c1'>, <class '__main__.p1'>, <class '__main__.c2'>, <class '__main__.p2'>, <class 'object'>)


In [6]:
class p1:
    def foo(self):
        print("foo from p1")
        
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")

class c1(p1):
    pass
class c2(p1):
    def bar(self):
        print("bar from c2")
        
class GC(c1,c2):
    pass

gc = GC()
gc.bar()
gc.foo()
print(GC.__mro__)


bar from c2
foo from p1
(<class '__main__.GC'>, <class '__main__.c1'>, <class '__main__.c2'>, <class '__main__.p1'>, <class 'object'>)


In [7]:
class p1:
    def foo(self):
        print("foo from p1")
        
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")

class c1(p2):
    pass
class c2(p1):
    def bar(self):
        print("bar from c2")
        
class GC(c1,c2):
    pass

gc = GC()
gc.bar()
gc.foo()
print(GC.__mro__)


bar from p2
foo from p2
(<class '__main__.GC'>, <class '__main__.c1'>, <class '__main__.p2'>, <class '__main__.c2'>, <class '__main__.p1'>, <class 'object'>)


In [9]:
class p1:
    def foo(self):
        print("foo from p1")
        
class p2:
    def foo(self):
        print("foo from p2")
    def bar(self):
        print("bar from p2")

class c1(p1,p2):
    pass
class c2(p1,p2):
    def bar(self):
        print("bar from c2")
        
class GC(c1,c2):
    pass

gc = GC()
gc.bar()
gc.foo()
print(GC.__mro__)


bar from c2
foo from p1
(<class '__main__.GC'>, <class '__main__.c1'>, <class '__main__.c2'>, <class '__main__.p1'>, <class '__main__.p2'>, <class 'object'>)


### Abstract Class
- Abstraction is implemented using abstract class
- Abstract class is created to declare a set of methods that must be created in any child class builton top of this abstract class
- Abstract method doesn't have any implementation
- Inheritance ABC class from module abc
@abstractmethod

In [12]:
from abc import ABC,abstractmethod
class shape(ABC):
    def __init__(self,shape_name):
        self.shape_name = shape_name
        
    @abstractmethod
    def draw(self):
        pass
    
class Circle(shape):
    def __init__(self):
        super().__init__("Circle")
    
    def draw(self):
        print("Draw circle")
        
c = Circle()
c.draw()

Draw circle


In [6]:
class a: pass
class b: pass
class c: pass
class d: pass
class e: pass
class f: pass
class k1(c,a,b): pass
class k3(a,d,f): pass
class k2(b,d,e): pass
class z(k1,k3,k2): pass
print(z.__mro__)

(<class '__main__.z'>, <class '__main__.k1'>, <class '__main__.c'>, <class '__main__.k3'>, <class '__main__.a'>, <class '__main__.k2'>, <class '__main__.b'>, <class '__main__.d'>, <class '__main__.f'>, <class '__main__.e'>, <class 'object'>)


### WAP Create staff class take name and salary as data members , the derived class teaching has subject as data memeber and class no-teaching has department as its data member. the derived class method overwrites the methods of base class 

In [5]:
class Staff:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary
        
    def display(self):
        print("This is the Staff class")
        print("Name:", self.name)
        print("Salary:", self.salary)
        print("---------------------------")
        
class Teaching(Staff):
    def __init__(self, name, salary, subject):
        super().__init__(name, salary) 
        self.subject = subject
    
    def display(self):
        print("This is the Teaching class")
        print("Name:", self.name)
        print("Salary:", self.salary)
        print("Subject:", self.subject)
        print("---------------------------")
        
class NonTeaching(Staff): 
    def __init__(self, name, salary, dep):
        super().__init__(name, salary) 
        self.dep = dep
    
    def display(self):
        print("This is the Non-Teaching class")
        print("Name:", self.name)
        print("Salary:", self.salary)
        print("Department:", self.dep)
        print("---------------------------")

st1 = Staff("Ishan", 100000)
st1.display()

ob2 = NonTeaching("Ishan", 10000, "IT")
ob2.display()

ob3 = Teaching("ishan",3000000,"PY")
ob3.display()

This is the Staff class
Name: Ishan
Salary: 100000
---------------------------
This is the Non-Teaching class
Name: Ishan
Salary: 10000
Department: IT
---------------------------
This is the Teaching class
Name: ishan
Salary: 3000000
Subject: PY
---------------------------


### Create a class called Student, having name and email as its data membersandm init(self, name, email) and putdata(self) as bound methods. Theinit function should assign the values passed as parameters to the requisitevariables. The putdata function should display the data of the student.Create another class called PhDguide having name, email, and students asits data members. Here, the students variable is the list of students underthe guide. The PhDguide class should have four bound methods: init,putdata, add, and remove. The init method should initialize the variables,the putdata should show the data of the guide, include the list of students,the add method should add a student to the list of students of the guideand the remove function should remove the student (if the student existsin the list of students of that guide) from the list of students.

In [ ]:
class Person:
    def __init__(self, name, email):
        self.name = name
        self.email = email
    
    def putdata(self):
        print("Name:", self.name)
        print("Email:", self.email)

class Student(Person):
    def __init__(self, name, email):
        super().__init__(name, email)

class PhDguide(Person):
    def __init__(self, name, email):
        super().__init__(name, email)
        self.students = []
    
    def putdata(self):
        super().putdata()
        print("Students:", [student.name for student in self.students])
    
    def add(self, student):
        self.students.append(student)
        print(f"{student.name} has been added to the list of students.")
    
    def remove(self, student):
        if student in self.students:
            self.students.remove(student)
            print(f"{student.name} has been removed from the list of students.")
        else:
            print(f"{student.name} is not in the list of students.")

student1 = Student("John Doe", "johndoe@example.com")
student1.putdata() 

guide1 = PhDguide("Jane Smith", "janesmith@example.com")
guide1.putdata() 

guide1.add(student1) 
guide1.putdata()  

guide1.remove(student1)  
guide1.putdata() 

### Create three Class Employee, Perks, NetSalary. Make an Employee class as an abstract class.Employee class should have methods for following tasks. - To get employee details like employee id,name and salary from user. - To print the Employee details. - return Salary. - An abstract methodemp_id. Perks class should have methods for following tasks. - To calculate DA, HRA, PF. - Toprint the individual and total of Perks (DA+HRA-PF). Netsalary class should have methods forfollowing tasks. - Calculate the total Salary after Perks. - Print employee detail also prints DA,HRA, PF and net salary.Note 1: DA-35%, HRA-17%, PF-12% Note 2: It is compulsory to create objects and demonstratingthe methods with Correct output. Example: Employee ID: 1 Employee Name: John EmployeeBasic Salary: 25000 DA: 8750.0 HRA: 4250.0 PF: 3000.0 Total Salary: 35000.0”


In [9]:
from abc import ABC, abstractmethod

class Employee(ABC):
    def __init__(self):
        self.emp_id = None
        self.name = None
        self.salary = None

    def get_employee_details(self):
        self.emp_id = int(input("Enter Employee ID: "))
        self.name = input("Enter Employee Name: ")
        self.salary = float(input("Enter Employee Basic Salary: "))
        
    @abstractmethod
    def emp_id(self):
        pass

    def print_employee_details(self):
        print("\nEmployee ID:", self.emp_id)
        print("Employee Name:", self.name)
        print("Employee Basic Salary:", self.salary)
        
    def get_salary(self):
        return self.salary

class Perks(Employee):
    def __init__(self):
        super().__init__()
        self.da = 0
        self.hra = 0
        self.pf = 0

    def calculate_perks(self):
        self.da = 0.35 * self.salary
        self.hra = 0.17 * self.salary
        self.pf = 0.12 * self.salary

    def print_perks(self):
        print("\nDA:", self.da)
        print("HRA:", self.hra)
        print("PF:", self.pf)
        print("Total Perks:", self.da + self.hra - self.pf)

class NetSalary(Perks):
    def __init__(self):
        super().__init__()
        self.net_salary = 0

    def calculate_net_salary(self):
        self.net_salary = self.salary + self.da + self.hra - self.pf

    def print_net_salary(self):
        self.print_employee_details()
        self.print_perks()
        print("Total Salary:", self.net_salary)

    def emp_id(self):
        pass

employee = NetSalary()

employee.get_employee_details()
employee.calculate_perks()
employee.calculate_net_salary()

employee.print_net_salary()
# employee.emp_id()

Enter Employee ID: 22
Enter Employee Name: ishan
Enter Employee Basic Salary: 1000000000

Employee ID: 22
Employee Name: ishan
Employee Basic Salary: 1000000000.0

DA: 350000000.0
HRA: 170000000.0
PF: 120000000.0
Total Perks: 400000000.0
Total Salary: 1400000000.0


In [14]:
class Bill:
    d = {"Hdd":5000,"Ram":2000,"Printer":600,"Pandrive":800}
    items = {"Hdd":0,"Ram":0,"Printer":0,"Pendrive":0}
    
    for i,j in d.items():
        print(i,j)
        accept = input("Want this item ? Y/N").upper()
        if accept == "Y":
            items[i] = int(input("Enter No. of"+i+"'s :"))*d[i]
        print()

    def __init__(self):
        print("1. Cash payment")
        print("2. Cheque payment")
        payment_method = int(input("Enter payment method :"))
        
        if payment_method == 1:
            CashPayment()
        elif payment_method == 2:
            cheque_no = int(input("Enter Cheque No :"))
            bank = input("Enter Bank name:")
            ChequePayment(cheque_no,bank)
            
class CashPayment(Bill):
    def __init__(self):
        print()
        print("Payment Method is Cash")
        sum = 0
        for i,j in self.items.items():
            sum += j
        print("Total Amount to pay :",sum)
        dic = {"2000 Note":2000,"500 Note":500,"200 Note":200,"100 Note":100,"50 Note":50,"20 Note":20,"10 Note":10}
        print()
        for i,j in dic.items():
            if sum >= j:
                print(i + ":" + sum//j)
                sum %= j
    
class ChequePayment(Bill):
    def __init__(self,cheque_no,bank):
        print()
        print("Payment method is by cheque")
        sum = 0
        for i,j in  self.itmes.items():
            sum+=j
        print("Total Amount to pay :",sum)
        print("Cheque no :",cheque_no)
        print("Bank name :",bank)
        
        
customer = Bill()

Hdd 5000
Want this item ? Y/Ny
Enter No. ofHdd's :3

Ram 2000
Want this item ? Y/Nn

Printer 600
Want this item ? Y/Nn

Pandrive 800
Want this item ? Y/Nn

1. Cash payment
2. Cheque payment
Enter payment method :2
Enter Cheque No :123456
Enter Bank name:yes bank

Payment method is by cheque


AttributeError: 'ChequePayment' object has no attribute 'itmes'

In [16]:
import numpy as np
arr1 = np.array([1,2,6,4,7,8,3])
print(np.sort(arr1))

arr2 = np.array([True,False,True])
print(np.sort(arr2))

arr3 = np.array([[3,4,6],[1,7,4],[4,2,5]])
print(np.sort(arr3,axis=0))
print()
arr4 = np.array([[[3,2,8],[7,9,3]],[[6,7,2],[9,6,4]]])
print(np.sort(arr4,axis=0))

[1 2 3 4 6 7 8]
[False  True  True]
[[1 2 4]
 [3 4 5]
 [4 7 6]]

[[[3 2 2]
  [7 6 3]]

 [[6 7 8]
  [9 9 4]]]
